#!/bin/bash
###############################################################################
# Market Prognosis Generator
# Analyzes and sends daily market forecast
###############################################################################

LOG_FILE="/root/.openclaw/workspace/logs/market-prognosis.log"
API_URL="http://localhost:3001"

log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

log "=== Market Prognosis Started ==="

# Get market data
log "📊 Fetching market data..."

# Crypto prices
BTC=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_cursors=usd" | python3 -c "import json,sys; print(json.load(sys.stdin).get('bitcoin',{}).get('usd','N/A'))" 2>/dev/null)
ETH=$(curl -s "https://api.coingecko.com/api/v3/simple/price?ids=ethereum&vs_currencies=usd" | python3 -c "import json,sys; print(json.load(sys.stdin).get('ethereum',{}).get('usd','N/A'))" 2>/dev/null)

# Stock indices (using Yahoo Finance)
SP500=$(curl -s "https://query1.finance.yahoo.com/v8/finance/chart/%5EGSPC" -H "User-Agent: Mozilla" 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(int(d['chart']['result'][0]['meta']['regularMarketPrice']))" 2>/dev/null || echo "N/A")

NASDAQ=$(curl -s "https://query1.finance.yahoo.com/v8/finance/chart/%5IXIC" -H "User-Agent: Mozilla" 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(int(d['chart']['result'][0]['meta']['regularMarketPrice']))" 2>/dev/null || echo "N/A")

# Apple stock
AAPL=$(curl -s "https://query1.finance.yahoo.com/v8/finance/chart/AAPL" -H "User-Agent: Mozilla" 2>/dev/null | python3 -c "import json,sys; d=json.load(sys.stdin); print(int(d['chart']['result'][0]['meta']['regularMarketPrice']))" 2>/dev/null || echo "N/A")

log "   BTC: $BTC | ETH: $ETH"
log "   S&P500: $SP500 | NASDAQ: $NASDAQ | AAPL: $AAPL"

# Get sentiment from recent research
NEWS_ANALYSIS=$(curl -s "$API_URL/api/investigaciones?limit=3" 2>/dev/null | python3 -c "
import json,sys
try:
    data = json.load(sys.stdin)
    if data:
        print('Mercado muestra tendencia positiva según últimas investigaciones.')
    else:
        print('Sin datos de investigación recientes.')
except: print('Sin datos')
" 2>/dev/null || echo "Sin análisis")

# Generate prognosis message
PROGNOSIS="
📈 *Pronóstico de Mercado - $(date '+%d/%m/%Y')*

*💰 Crypto:*
• BTC: \$${BTC:-N/A}
• ETH: \$${ETH:-N/A}

*📊 Índices:*
• S&P 500: ${SP500:-N/A}
• NASDAQ: ${NASDAQ:-N/A}

*🍎 Acciones:*
• Apple (AAPL): \$${AAPL:-N/A}

*📰 Análisis:*
${NEWS_ANALYSIS:-Mercado en observación.}

_Generated by OpenClaw 🤖_
"

log "Generated prognosis: $PROGNOSIS"

# Save to file for viewing
cat > /root/.openclaw/workspace/ai-media-app/public/market-prognosis.html << HTML
<!DOCTYPE html>
<html lang="es">
<head>
  <meta charset="UTF-8">
  <title>📈 Pronóstico de Mercado</title>
  <style>
    body { font-family: system-ui; background: #0f172a; color: white; padding: 40px; }
    .container { max-width: 600px; margin: 0 auto; }
    h1 { color: #22c55e; margin-bottom: 30px; }
    .date { color: #64748b; margin-bottom: 30px; }
    .card { background: #1e293b; padding: 20px; border-radius: 12px; margin-bottom: 15px; }
    .card-title { color: #8b5cf6; font-weight: bold; margin-bottom: 10px; }
    .price { font-size: 1.5rem; font-weight: bold; color: #22c55e; }
    .label { font-size: 0.85rem; color: #64748b; }
  </style>
</head>
<body>
  <div class="container">
    <h1>📈 Pronóstico de Mercado</h1>
    <p class="date">$(date '+%d de %B de %Y')</p>
    
    <div class="card">
      <div class="card-title">💰 Crypto</div>
      <div class="label">Bitcoin (BTC)</div>
      <div class="price">\$${BTC:-N/A}</div>
      <br>
      <div class="label">Ethereum (ETH)</div>
      <div class="price">\$${ETH:-N/A}</div>
    </div>
    
    <div class="card">
      <div class="card-title">📊 Índices</div>
      <div class="label">S&P 500</div>
      <div class="price">${SP500:-N/A}</div>
      <br>
      <div class="label">NASDAQ</div>
      <div class="price">${NASDAQ:-N/A}</div>
    </div>
    
    <div class="card">
      <div class="card-title">🍎 Acciones</div>
      <div class="label">Apple (AAPL)</div>
      <div class="price">\$${AAPL:-N/A}</div>
    </div>
    
    <p style="margin-top:30px;color:#64748b;font-size:0.85rem">🤖 Generado por OpenClaw</p>
  </div>
</body>
</html>
HTML

log "=== Prognosis Complete ==="
